server:
  port: ${PORT:${SERVERS_PORT:0}}

spring:
  application:
    name: ms-catalogo-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ms_catalogo
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8065/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
