server:
  port: 9065

spring:
  application:
    name: ms-gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      routes:
        - id: ms-catalogo-service
          uri: lb://ms-catalogo-service
          predicates:
            - Path=/products/**
          filters:
            - name: AuthFilter

        - id: ms-compra-service
          uri: lb://ms-compra-service
          predicates:
            - Path=/purchases/**,/suppliers/**
          filters:
            - name: AuthFilter

        - id: ms-inventario-service
          uri: lb://ms-inventario-service
          predicates:
            - Path=/inventory/**,/accounting/**
          filters:
            - name: AuthFilter

        - id: ms-venta-service
          uri: lb://ms-venta-service
          predicates:
            - Path=/sales/**,/customers/**
          filters:
            - name: AuthFilter

        - id: ms-auth-service
          uri: lb://ms-auth-service
          predicates:
            - Path=/auth/**
          filters: []

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8065/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
